[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[colors]
draw_bold_text_with_bright_colors = true

# Colors (Gruvbox dark)

[colors.primary]
background = '0x282828' # hard contrast: '0x1d2021', soft contrast: '0x32302f'
foreground = '0xebdbb2'

[colors.normal]
black = '0x282828'
red = '0xcc241d'
green = '0x98971a'
yellow = '0xd79921'
blue = '0x458588'
magenta = '0xb16286'
cyan = '0x689d6a'
white = '0xa89984'

[colors.bright]
black = '0x928374'
red = '0xfb4934'
green = '0xb8bb26'
yellow = '0xfabd2f'
blue = '0x83a598'
magenta = '0xd3869b'
cyan = '0x8ec07c'
white = '0xebdbb2'

# Colors (Gruvbox dark) end

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.padding]
x = 6
y = 6

[keyboard]
bindings = [
  { key = "Left", mods = "Control", chars = "\u001BB" },
  { key = "Right", mods = "Control", chars = "\u001BF" }
]
